### Create a new user
POST https://eduplay.jisuheo.shop/auth/signup
Content-Type: application/json

{
    "name": "user1",
    "email": "user1@gmail.com",
    "password": "1234",
    "level": 1,
    "matchedNum": 0
}

### login 
POST https://eduplay.jisuheo.shop/login
Content-Type: application/json

{
    "email": "sparta2@sparta.com",
    "password": "qwer1234"
}

### Create a new user
POST http://localhost:8000/auth/signup
Content-Type: application/json

{
    "name": "user1",
    "email": "user1@gmail.com",
    "password": "1234",
    "level": 1,
    "matchedNum": 0
}

### 
POST http://localhost:8000/auth/login
Content-Type: application/json

{
    "email": "user1@gmail.com",
    "password": "1234"
}