### Create a new user
POST http://localhost:8000/auth/signup
Content-Type: application/json

{
    "name": "sparta4",
    "email": "sparta4@sparta.com",
    "password": "qwer1234",
    "level": 1
}

### login 
POST http://localhost:8000/auth/login
Content-Type: application/json

{
    "email": "sparta2@sparta.com",
    "password": "qwer1234"
}